"""Add correct_answer and wrong_answer to words table

Revision ID: a96a7f2a947a
Revises: 
Create Date: 2025-10-22 16:49:50.576641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96a7f2a947a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('correct_answers', sa.Integer(), nullable=False))
    op.add_column('words', sa.Column('wrong_answers', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'wrong_answers')
    op.drop_column('words', 'correct_answers')
    # ### end Alembic commands ###
